from __future__ import annotations
from backend.src.models.base import Base
from backend.src.models.fase import Fase
from backend.src.models.fase_mata_mata import FaseMataMata
from backend.src.models.partida import Partida
from backend.src.models.rodada import Rodada
from backend.src.models.time import Time
from backend.src.models.torneio import Torneio
from backend.src.models.torneio_time import TorneioTime
from backend.src.models.torneio_usuario import TorneioUsuario
from backend.src.models.usuario import Usuario
from backend.src.models.usuario_time import UsuarioTime