from enum import Enum


class TipoTorneio(str, Enum):
    INDIVIDUAL = "INDIVIDUAL"
    EQUIPE = "EQUIPE"

class EstadoTorneio(str, Enum):
    CRIADO = "CRIADO"
    INSCRICOES_ABERTAS = "INSCRICOES_ABERTAS"
    INSCRICOES_ENCERRADAS = "INSCRICOES_ENCERRADAS"
    EM_ANDAMENTO = "EM_ANDAMENTO"
    FINALIZADO = "FINALIZADO"
    CANCELADO = "CANCELADO" 