from __future__ import annotations
from models.base import Base
from models.fase import Fase
from models.fase_mata_mata import FaseMataMata
from models.partida import Partida
from models.rodada import Rodada
from models.time import Time
from models.torneio import Torneio
from models.torneio_time import TorneioTime
from models.torneio_usuario import TorneioUsuario
from models.usuario import Usuario
from models.usuario_time import UsuarioTime